#!/usr/bin/env bash

test ! -x /usr/local/bin/lazygit || exit

LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
pushd /tmp 2>&1 >/dev/null
curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
tar xf lazygit.tar.gz lazygit && rm lazygit.tar.gz
install lazygit /usr/local/bin && rm lazygit
popd /tmp 2>&1 >/dev/null
